"""Initial migration

Revision ID: 349bdaefd9af
Revises: 
Create Date: 2023-09-19 06:28:22.462013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349bdaefd9af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animais',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('numero_brinco', sa.Integer(), nullable=True),
    sa.Column('data_nascimento', sa.DateTime(), nullable=True),
    sa.Column('sexo', sa.String(length=100), nullable=True),
    sa.Column('raca', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarefas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('publicado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarefas')
    op.drop_table('animais')
    # ### end Alembic commands ###
